DROP TABLE IF EXISTS `facts_figures_norm`;
CREATE TABLE IF NOT EXISTS `facts_figures_norm` (
  `INDICATOR_ID` smallint(6) DEFAULT NULL,
  `SPLIT_1` varchar(255) DEFAULT NULL,
  `SPLIT_2` varchar(255) DEFAULT NULL,
  `SPLIT_3` varchar(255) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `REGION` varchar(15) DEFAULT NULL,
  `COUNTRY` varchar(50) DEFAULT NULL,
  `MEASURE` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
